# Generated by Django 5.0.4 on 2026-03-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text_uz', models.TextField(blank=True, null=True)),
                ('text_ru', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scripts/')),
                ('repeat_type', models.CharField(choices=[('once', 'Bir marta'), ('monthly', 'Har oy')], default='once', max_length=20)),
                ('send_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(to='scripts.group')),
            ],
        ),
    ]
