# Generated by Django 5.0.4 on 2026-03-12 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_alter_group_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='script',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='scripts', to='scripts.group'),
        ),
        migrations.AlterField(
            model_name='script',
            name='repeat_type',
            field=models.CharField(choices=[('once', 'Bir marta'), ('daily', 'Har kuni'), ('monthly', 'Har oy')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='scripts.branch'),
        ),
        migrations.AddField(
            model_name='script',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='scripts', to='scripts.branch'),
        ),
    ]
